### ISSUE TITLE
klse and sgx on SectorsID

### ISSUE THREAD

**Issue by onlyphantom** [supertypeai/sectors-kb#11]
### Desired Result

Create sectors.app/malaysia and sectors.app/singapore with basic overview of the KLSE and SGX financial market

### Requirements

- [ ] Data pipelines for these data (@Christeigen)
- [ ] Scheduled updater (@Christeigen)
- [ ] Front end views (@onlyphantom)
- [ ] Add to sitemap and incorporate into rest of sectors (@onlyphantom)
