### ISSUE TITLE
News on SectorsID

### ISSUE THREAD

**Issue by onlyphantom** [supertypeai/sectors-kb#12]
### Desired Result

Whenever you go a sector page, you should see high-quality news happening in that sector.

IDN Financials, Yahoo Finance, Bloomberg are good sources, but we should also consider alternative sources such as:
- https://minerba.esdm.go.id/lelang/
- https://dash.datalpse.com/ (if you need a paid account, ask @onlyphantom)

A high quality news article is one that is:
- actionable
- commercially valuable (request for proposal on a new coal site)
- big movement of money (merger and acquisitions, large insider purchase etc)
- potential big changes for market cap in the industry

If implemented well, navigating to a sector page should bring to the reader's attention a list of high-quality, attention-worthy news

### Requirements
- [ ] Research and shortlist
- [ ] Data pipelines for these data (needs to build a quality-ranking engine, and rank each article with a quality score)
- [ ] Scheduled updater
- [ ] Front end views (@onlyphantom)
- [ ] Add to sitemap and incorporate into rest of sectors (@onlyphantom)
